// Home Design Color Packs with comprehensive color options and alternatives
// Helper function to generate color variations
const generateColorVariations = (baseColor, count = 10) => {
  const variations = [];
  const normalized = baseColor.replace('#', '');
  const bigint = parseInt(normalized, 16);
  const r = (bigint >> 16) & 255;
  const g = (bigint >> 8) & 255;
  const b = bigint & 255;
  
  for (let i = 0; i < count; i++) {
    const factor = 1 - (i * 0.08);
    const newR = Math.round(r * factor);
    const newG = Math.round(g * factor);
    const newB = Math.round(b * factor);
    const hex = `#${newR.toString(16).padStart(2, '0')}${newG.toString(16).padStart(2, '0')}${newB.toString(16).padStart(2, '0')}`.toUpperCase();
    variations.push(hex);
  }
  return variations;
};

// Helper function to create color options with alternatives
const createColorOptions = (primary, secondary, accent, neutral) => {
  return {
    primary: {
      base: primary,
      alternatives: generateColorVariations(primary, 5),
    },
    secondary: {
      base: secondary,
      alternatives: generateColorVariations(secondary, 5),
    },
    accent: {
      base: accent,
      alternatives: generateColorVariations(accent, 5),
    },
    neutral: {
      base: neutral,
      alternatives: generateColorVariations(neutral, 5),
    },
  };
};

const homeDesignPacks = [
  // LUXE & ELEGANT (1-15)
  {
    id: 1,
    category: 'Luxe & Elegant',
    name: 'Ivory Opulence',
    description: 'Sophisticated ivory base with gold accents',
    rooms: ['Living Room', 'Dining Room'],
    colors: createColorOptions('#FFFFF0', '#FAF6F1', '#DAA520', '#64748B'),
  },
  {
    id: 2,
    category: 'Luxe & Elegant',
    name: 'Navy Majesty',
    description: 'Deep navy walls with cream accents',
    rooms: ['Library', 'Home Office', 'Bedroom'],
    colors: createColorOptions('#0F1419', '#1A2942', '#FFFDD0', '#FFFFFF'),
  },
  {
    id: 3,
    category: 'Luxe & Elegant',
    name: 'Charcoal Elegance',
    description: 'Rich charcoal with rose gold details',
    rooms: ['Master Bedroom', 'Lounge'],
    colors: createColorOptions('#36454F', '#2F4F4F', '#B76E79', '#C0C0C0'),
  },
  {
    id: 4,
    category: 'Luxe & Elegant',
    name: 'Emerald Dreams',
    description: 'Jewel-toned emerald with gold trim',
    rooms: ['Master Bedroom', 'Dining Room'],
    colors: createColorOptions('#004D40', '#00695C', '#FFD700', '#D4AF37'),
  },
  {
    id: 5,
    category: 'Luxe & Elegant',
    name: 'Plum Velvet',
    description: 'Deep plum with burgundy and gold',
    rooms: ['Master Bedroom', 'Lounge'],
    colors: createColorOptions('#4A148C', '#6A1B9A', '#8B0000', '#DAA520'),
  },
  {
    id: 6,
    category: 'Luxe & Elegant',
    name: 'Sapphire Serenity',
    description: 'Rich sapphire with silver accents',
    rooms: ['Master Suite', 'Library'],
    colors: createColorOptions('#0F3460', '#16213E', '#E94560', '#C0C0C0'),
  },
  {
    id: 7,
    category: 'Luxe & Elegant',
    name: 'Gold Cascade',
    description: 'Warm gold with chocolate accents',
    rooms: ['Dining Room', 'Master Bedroom'],
    colors: createColorOptions('#B8860B', '#CD853F', '#8B4513', '#D4AF37'),
  },
  {
    id: 8,
    category: 'Luxe & Elegant',
    name: 'Burgundy Bliss',
    description: 'Deep burgundy with cream trim',
    rooms: ['Wine Room', 'Master Bedroom'],
    colors: createColorOptions('#800020', '#A71D31', '#F5F5DC', '#8B0000'),
  },
  {
    id: 9,
    category: 'Luxe & Elegant',
    name: 'Slate Sophistication',
    description: 'Slate gray with pearl accents',
    rooms: ['Library', 'Home Office'],
    colors: createColorOptions('#2F4F4F', '#36454F', '#FFF8DC', '#696969'),
  },
  {
    id: 10,
    category: 'Luxe & Elegant',
    name: 'Teal Tranquility',
    description: 'Deep teal with gold details',
    rooms: ['Master Bedroom', 'Bathroom'],
    colors: createColorOptions('#008080', '#20B2AA', '#FFD700', '#D4AF37'),
  },
  {
    id: 11,
    category: 'Luxe & Elegant',
    name: 'Marble Mystique',
    description: 'Cool marble with black accents',
    rooms: ['Foyer', 'Living Room'],
    colors: createColorOptions('#E8E8E8', '#D3D3D3', '#1F1F1F', '#A9A9A9'),
  },
  {
    id: 12,
    category: 'Luxe & Elegant',
    name: 'Crimson Crown',
    description: 'Royal crimson with gold trim',
    rooms: ['Master Bedroom', 'Drawing Room'],
    colors: createColorOptions('#DC143C', '#8B0000', '#FFD700', '#DAA520'),
  },
  {
    id: 13,
    category: 'Luxe & Elegant',
    name: 'Pearl Palace',
    description: 'Soft pearl with silver accents',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#FDEEF4', '#F0F0F0', '#C0C0C0', '#E8D8E8'),
  },
  {
    id: 14,
    category: 'Luxe & Elegant',
    name: 'Obsidian Night',
    description: 'Deep obsidian with metallic accents',
    rooms: ['Media Room', 'Master Bedroom'],
    colors: createColorOptions('#0B0C0C', '#1A1A1A', '#B8B8B8', '#2F2F2F'),
  },
  {
    id: 15,
    category: 'Luxe & Elegant',
    name: 'Champagne Dreams',
    description: 'Elegant champagne with blush accents',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#F7E7CE', '#E8DCC1', '#E8B4D4', '#D4B4A1'),
  },

  // MODERN MINIMALIST (16-30)
  {
    id: 16,
    category: 'Modern Minimalist',
    name: 'Pure White',
    description: 'Crisp white minimalist aesthetic',
    rooms: ['Any Room'],
    colors: createColorOptions('#FFFFFF', '#FAFAFA', '#F5F5F5', '#E0E0E0'),
  },
  {
    id: 17,
    category: 'Modern Minimalist',
    name: 'Soft Gray',
    description: 'Gentle cool gray tones',
    rooms: ['Bedroom', 'Home Office', 'Living Room'],
    colors: createColorOptions('#D3D3D3', '#C0C0C0', '#808080', '#A9A9A9'),
  },
  {
    id: 18,
    category: 'Modern Minimalist',
    name: 'Concrete Modern',
    description: 'Industrial concrete aesthetic',
    rooms: ['Loft', 'Studio'],
    colors: createColorOptions('#A0A0A0', '#808080', '#404040', '#696969'),
  },
  {
    id: 19,
    category: 'Modern Minimalist',
    name: 'Scandinavian Cool',
    description: 'Nordic whites and light grays',
    rooms: ['Kitchen', 'Bedroom'],
    colors: createColorOptions('#F8F8F8', '#E8E8E8', '#1A1A1A', '#C0C0C0'),
  },
  {
    id: 20,
    category: 'Modern Minimalist',
    name: 'Monochrome Zen',
    description: 'Black and white harmony',
    rooms: ['Living Room', 'Studio'],
    colors: createColorOptions('#1F1F1F', '#4F4F4F', '#FFFFFF', '#BFBFBF'),
  },
  {
    id: 21,
    category: 'Modern Minimalist',
    name: 'Carbon Steel',
    description: 'Cool carbon steel tones',
    rooms: ['Home Office', 'Kitchen'],
    colors: createColorOptions('#36454F', '#2C3E50', '#FFFFFF', '#7F8C8D'),
  },
  {
    id: 22,
    category: 'Modern Minimalist',
    name: 'Ash Silence',
    description: 'Soft ash colors with white trim',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#B2B2B2', '#A0A0A0', '#FFFFFF', '#808080'),
  },
  {
    id: 23,
    category: 'Modern Minimalist',
    name: 'Neutral Canvas',
    description: 'Taupe and cream minimalist',
    rooms: ['Living Room', 'Any Room'],
    colors: createColorOptions('#B38B6D', '#A0826D', '#F5F5DC', '#8B7355'),
  },
  {
    id: 24,
    category: 'Modern Minimalist',
    name: 'Light & Airy',
    description: 'Super light minimal palette',
    rooms: ['Kitchen', 'Living Room'],
    colors: createColorOptions('#FFFAF0', '#FAFAFA', '#DCDCDC', '#F0F0F0'),
  },
  {
    id: 25,
    category: 'Modern Minimalist',
    name: 'Deep Minimal',
    description: 'Dark minimal aesthetic',
    rooms: ['Bedroom', 'Media Room'],
    colors: createColorOptions('#1A1A1A', '#2F2F2F', '#F5F5F5', '#505050'),
  },
  {
    id: 26,
    category: 'Modern Minimalist',
    name: 'Pearl Gray',
    description: 'Pearl with gray accents',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#E8E8E8', '#D3D3D3', '#4F4F4F', '#BFBFBF'),
  },
  {
    id: 27,
    category: 'Modern Minimalist',
    name: 'Glacier White',
    description: 'Bright glacier with cool grays',
    rooms: ['Kitchen', 'Bathroom'],
    colors: createColorOptions('#F0F8FF', '#FFFAFA', '#708090', '#D3D3D3'),
  },
  {
    id: 28,
    category: 'Modern Minimalist',
    name: 'Subtle Contrast',
    description: 'Subtle black and white contrast',
    rooms: ['Home Office', 'Living Room'],
    colors: createColorOptions('#FAFAFA', '#F0F0F0', '#2F2F2F', '#BFBFBF'),
  },
  {
    id: 29,
    category: 'Modern Minimalist',
    name: 'Minimalist Warm',
    description: 'Warm minimalist with beige',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#FFFACD', '#F5F5DC', '#8B8680', '#E0D5D0'),
  },
  {
    id: 30,
    category: 'Modern Minimalist',
    name: 'Steel Spirit',
    description: 'Cool steel with white accents',
    rooms: ['Home Office', 'Studio'],
    colors: createColorOptions('#70808B', '#36454F', '#FFFFFF', '#9CA3A9'),
  },

  // WARM & COZY (31-45)
  {
    id: 31,
    category: 'Warm & Cozy',
    name: 'Autumn Embrace',
    description: 'Warm autumn tones throughout',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#CD853F', '#D2691E', '#8B4513', '#DEB887'),
  },
  {
    id: 32,
    category: 'Warm & Cozy',
    name: 'Honey Warmth',
    description: 'Golden honey with warm accents',
    rooms: ['Kitchen', 'Dining Room'],
    colors: createColorOptions('#FFB366', '#FF9944', '#8B4513', '#FFD699'),
  },
  {
    id: 33,
    category: 'Warm & Cozy',
    name: 'Terracotta Heart',
    description: 'Earthy terracotta tones',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#CC5500', '#E97451', '#8B4513', '#D2B48C'),
  },
  {
    id: 34,
    category: 'Warm & Cozy',
    name: 'Burnt Sienna',
    description: 'Rich burnt sienna warmth',
    rooms: ['Master Bedroom', 'Living Room'],
    colors: createColorOptions('#E13C2E', '#A0522D', '#654321', '#D2B48C'),
  },
  {
    id: 35,
    category: 'Warm & Cozy',
    name: 'Caramel Comfort',
    description: 'Caramel tones throughout',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#A0522D', '#8B6914', '#CD853F', '#DEB887'),
  },
  {
    id: 36,
    category: 'Warm & Cozy',
    name: 'Peach Blush',
    description: 'Soft peach with warm accents',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#FFDAB9', '#FFCCCB', '#E97451', '#FAAAA8'),
  },
  {
    id: 37,
    category: 'Warm & Cozy',
    name: 'Copper Glow',
    description: 'Warm copper with rich accents',
    rooms: ['Dining Room', 'Living Room'],
    colors: createColorOptions('#B87333', '#CC6600', '#8B4513', '#D2691E'),
  },
  {
    id: 38,
    category: 'Warm & Cozy',
    name: 'Chocolate Comfort',
    description: 'Rich chocolate warmth',
    rooms: ['Living Room', 'Master Bedroom'],
    colors: createColorOptions('#654321', '#5C4033', '#8B4513', '#A0826D'),
  },
  {
    id: 39,
    category: 'Warm & Cozy',
    name: 'Sunset Glow',
    description: 'Warm sunset colors',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#FF7F50', '#FF6347', '#CD5C5C', '#FFB88C'),
  },
  {
    id: 40,
    category: 'Warm & Cozy',
    name: 'Spice Palette',
    description: 'Warm spice tones',
    rooms: ['Kitchen', 'Dining Room'],
    colors: createColorOptions('#CC5500', '#B8860B', '#8B4513', '#D2B48C'),
  },
  {
    id: 41,
    category: 'Warm & Cozy',
    name: 'Rustic Charm',
    description: 'Rustic warm charm',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#8B5A3C', '#A0826D', '#654321', '#D2B48C'),
  },
  {
    id: 42,
    category: 'Warm & Cozy',
    name: 'Warm Sand',
    description: 'Warm sand tones',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#EDC9AF', '#DEB887', '#CD853F', '#F5DEB3'),
  },
  {
    id: 43,
    category: 'Warm & Cozy',
    name: 'Brick & Mortar',
    description: 'Warm brick tones',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#A0522D', '#8B4513', '#654321', '#D2B48C'),
  },
  {
    id: 44,
    category: 'Warm & Cozy',
    name: 'Apricot Dreams',
    description: 'Soft apricot warmth',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#FFB366', '#FFDAB9', '#FF9966', '#FFCCCB'),
  },
  {
    id: 45,
    category: 'Warm & Cozy',
    name: 'Wheat Fields',
    description: 'Golden wheat tones',
    rooms: ['Kitchen', 'Living Room'],
    colors: createColorOptions('#F5DEB3', '#DAA520', '#B8860B', '#FFD700'),
  },

  // COOL & SERENE (46-60)
  {
    id: 46,
    category: 'Cool & Serene',
    name: 'Ocean Breeze',
    description: 'Calm ocean blue tones',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#E0FFFF', '#AFEEEE', '#20B2AA', '#87CEEB'),
  },
  {
    id: 47,
    category: 'Cool & Serene',
    name: 'Sky Blue Serenity',
    description: 'Soft sky blue throughout',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#87CEEB', '#ADD8E6', '#4682B4', '#B0E0E6'),
  },
  {
    id: 48,
    category: 'Cool & Serene',
    name: 'Mint Fresh',
    description: 'Fresh mint green',
    rooms: ['Kitchen', 'Bathroom'],
    colors: createColorOptions('#F0FFFF', '#AFEEEE', '#3EB489', '#5FDC9C'),
  },
  {
    id: 49,
    category: 'Cool & Serene',
    name: 'Aqua Dreams',
    description: 'Peaceful aqua tones',
    rooms: ['Bedroom', 'Spa'],
    colors: createColorOptions('#7FFFD4', '#AFEEEE', '#20B2AA', '#5FD5D5'),
  },
  {
    id: 50,
    category: 'Cool & Serene',
    name: 'Lavender Calm',
    description: 'Soothing lavender',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#E6E6FA', '#DDA0DD', '#9370DB', '#B19CD9'),
  },
  {
    id: 51,
    category: 'Cool & Serene',
    name: 'Soft Sage',
    description: 'Soft sage green',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#C0D4C0', '#9DC183', '#6B8E23', '#A9BE9C'),
  },
  {
    id: 52,
    category: 'Cool & Serene',
    name: 'Powder Blue',
    description: 'Light powder blue',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#B0E0E6', '#ADD8E6', '#4682B4', '#87CEEB'),
  },
  {
    id: 53,
    category: 'Cool & Serene',
    name: 'Misty Gray',
    description: 'Misty cool gray',
    rooms: ['Bedroom', 'Home Office'],
    colors: createColorOptions('#D3D3D3', '#B0C4DE', '#778899', '#BEBEBE'),
  },
  {
    id: 54,
    category: 'Cool & Serene',
    name: 'Pale Turquoise',
    description: 'Pale turquoise calm',
    rooms: ['Bathroom', 'Bedroom'],
    colors: createColorOptions('#AFEEEE', '#7FFFD4', '#40E0D0', '#20B2AA'),
  },
  {
    id: 55,
    category: 'Cool & Serene',
    name: 'Cool Eucalyptus',
    description: 'Cool eucalyptus tones',
    rooms: ['Bathroom', 'Living Room'],
    colors: createColorOptions('#C5E1A5', '#9CCC65', '#689F38', '#B3E5FC'),
  },
  {
    id: 56,
    category: 'Cool & Serene',
    name: 'Icy Mint',
    description: 'Icy cool mint',
    rooms: ['Kitchen', 'Bathroom'],
    colors: createColorOptions('#E0FFFF', '#B2DFDB', '#4DB6AC', '#80CBC4'),
  },
  {
    id: 57,
    category: 'Cool & Serene',
    name: 'Periwinkle Peace',
    description: 'Soft periwinkle',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#E6E6FA', '#D8BFD8', '#DDA0DD', '#BA55D3'),
  },
  {
    id: 58,
    category: 'Cool & Serene',
    name: 'Steel Blue Zen',
    description: 'Cool steel blue',
    rooms: ['Home Office', 'Bedroom'],
    colors: createColorOptions('#4682B4', '#5F9EA0', '#36454F', '#87CEEB'),
  },
  {
    id: 59,
    category: 'Cool & Serene',
    name: 'Icy Azure',
    description: 'Cool icy azure',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#F0FFFF', '#E0FFFF', '#ADD8E6', '#87CEEB'),
  },
  {
    id: 60,
    category: 'Cool & Serene',
    name: 'Glacial Peace',
    description: 'Glacial cool peace',
    rooms: ['Bedroom', 'Spa'],
    colors: createColorOptions('#E8F4F8', '#D0E8F2', '#7DB8C4', '#A8D8E8'),
  },

  // VIBRANT & BOLD (61-75)
  {
    id: 61,
    category: 'Vibrant & Bold',
    name: 'Electric Blue',
    description: 'Bold electric blue',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#0066FF', '#0047AB', '#003366', '#4169E1'),
  },
  {
    id: 62,
    category: 'Vibrant & Bold',
    name: 'Vivid Green',
    description: 'Vibrant vivid green',
    rooms: ['Kitchen', 'Living Room'],
    colors: createColorOptions('#00FF00', '#00CC00', '#008000', '#32CD32'),
  },
  {
    id: 63,
    category: 'Vibrant & Bold',
    name: 'Hot Pink Energy',
    description: 'Bold hot pink',
    rooms: ['Bedroom', 'Studio'],
    colors: createColorOptions('#FF1493', '#FF69B4', '#FF00FF', '#FF69B4'),
  },
  {
    id: 64,
    category: 'Vibrant & Bold',
    name: 'Sunset Orange',
    description: 'Bold sunset orange',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#FF6600', '#FF5500', '#FF8C00', '#FFB84D'),
  },
  {
    id: 65,
    category: 'Vibrant & Bold',
    name: 'Neon Purple',
    description: 'Bold neon purple',
    rooms: ['Bedroom', 'Studio'],
    colors: createColorOptions('#9933FF', '#7700FF', '#6600CC', '#AA44FF'),
  },
  {
    id: 66,
    category: 'Vibrant & Bold',
    name: 'Turquoise Pop',
    description: 'Bold turquoise',
    rooms: ['Kitchen', 'Bathroom'],
    colors: createColorOptions('#00CCFF', '#00BBDD', '#0099CC', '#1AC5D1'),
  },
  {
    id: 67,
    category: 'Vibrant & Bold',
    name: 'Lime Zest',
    description: 'Bold lime green',
    rooms: ['Kitchen', 'Studio'],
    colors: createColorOptions('#CCFF00', '#FFFF00', '#CCDD00', '#AADD11'),
  },
  {
    id: 68,
    category: 'Vibrant & Bold',
    name: 'Coral Burst',
    description: 'Bold coral colors',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#FF7F50', '#FF6347', '#FF4500', '#FFA07A'),
  },
  {
    id: 69,
    category: 'Vibrant & Bold',
    name: 'Magenta Magic',
    description: 'Bold magenta',
    rooms: ['Bedroom', 'Studio'],
    colors: createColorOptions('#FF00FF', '#FF1493', '#EE82EE', '#FF69B4'),
  },
  {
    id: 70,
    category: 'Vibrant & Bold',
    name: 'Sunny Yellow',
    description: 'Bold sunny yellow',
    rooms: ['Kitchen', 'Living Room'],
    colors: createColorOptions('#FFFF00', '#FFD700', '#FFA500', '#FFCC00'),
  },
  {
    id: 71,
    category: 'Vibrant & Bold',
    name: 'Red Hot',
    description: 'Bold red hot',
    rooms: ['Dining Room', 'Living Room'],
    colors: createColorOptions('#FF0000', '#CC0000', '#990000', '#FF4444'),
  },
  {
    id: 72,
    category: 'Vibrant & Bold',
    name: 'Teal Thunder',
    description: 'Bold teal',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#008080', '#00CCCC', '#00BBDD', '#20B2AA'),
  },
  {
    id: 73,
    category: 'Vibrant & Bold',
    name: 'Violet Vibes',
    description: 'Bold violet',
    rooms: ['Bedroom', 'Studio'],
    colors: createColorOptions('#EE82EE', '#DDA0DD', '#9370DB', '#BA55D3'),
  },
  {
    id: 74,
    category: 'Vibrant & Bold',
    name: 'Tangerine Dream',
    description: 'Bold tangerine',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#FF8C00', '#FF7F50', '#FF6347', '#FFA07A'),
  },
  {
    id: 75,
    category: 'Vibrant & Bold',
    name: 'Emerald Pop',
    description: 'Bold emerald',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#50C878', '#3CB371', '#228B22', '#32CD32'),
  },

  // NATURAL & EARTHY (76-90)
  {
    id: 76,
    category: 'Natural & Earthy',
    name: 'Forest Floor',
    description: 'Deep forest green',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#228B22', '#1F4D40', '#355E3B', '#2F5233'),
  },
  {
    id: 77,
    category: 'Natural & Earthy',
    name: 'Earth Brown',
    description: 'Natural earth brown',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#8B4513', '#654321', '#5C4033', '#A0826D'),
  },
  {
    id: 78,
    category: 'Natural & Earthy',
    name: 'Clay Tones',
    description: 'Natural clay tones',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#A0826D', '#8B6F47', '#996600', '#C8956E'),
  },
  {
    id: 79,
    category: 'Natural & Earthy',
    name: 'Stone Sage',
    description: 'Stone gray with sage',
    rooms: ['Living Room', 'Bathroom'],
    colors: createColorOptions('#A0A0A0', '#9DC183', '#6B8E23', '#8B8680'),
  },
  {
    id: 80,
    category: 'Natural & Earthy',
    name: 'Moss Green',
    description: 'Soft moss green',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#8A9B83', '#7BA56D', '#6B8E23', '#9DC183'),
  },
  {
    id: 81,
    category: 'Natural & Earthy',
    name: 'Sand Dunes',
    description: 'Warm sand tones',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#DAA520', '#D2B48C', '#F5DEB3', '#CDAA7D'),
  },
  {
    id: 82,
    category: 'Natural & Earthy',
    name: 'Olive Garden',
    description: 'Soft olive green',
    rooms: ['Living Room', 'Dining Room'],
    colors: createColorOptions('#808000', '#6B8E23', '#9ACD32', '#A4AC86'),
  },
  {
    id: 83,
    category: 'Natural & Earthy',
    name: 'Mud & Stone',
    description: 'Gray-brown earth tones',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#8B8680', '#A0826D', '#696969', '#A9A9A9'),
  },
  {
    id: 84,
    category: 'Natural & Earthy',
    name: 'Wood Smoke',
    description: 'Warm wood smoke gray',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#A9A9A9', '#8B8680', '#696969', '#808080'),
  },
  {
    id: 85,
    category: 'Natural & Earthy',
    name: 'Fern Whisper',
    description: 'Soft fern green',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#9DC183', '#8A9B83', '#6B8E23', '#7BA56D'),
  },
  {
    id: 86,
    category: 'Natural & Earthy',
    name: 'Copper Leaf',
    description: 'Warm copper leaf tones',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#B87333', '#A0826D', '#8B6914', '#D2691E'),
  },
  {
    id: 87,
    category: 'Natural & Earthy',
    name: 'Granite Gray',
    description: 'Natural granite tones',
    rooms: ['Kitchen', 'Bathroom'],
    colors: createColorOptions('#808080', '#696969', '#A9A9A9', '#8B8680'),
  },
  {
    id: 88,
    category: 'Natural & Earthy',
    name: 'Lichen Blend',
    description: 'Soft lichen gray-green',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#9CA99C', '#8B8680', '#7BA56D', '#96A89C'),
  },
  {
    id: 89,
    category: 'Natural & Earthy',
    name: 'Oak Wood',
    description: 'Warm oak wood tones',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#A0826D', '#996633', '#8B6F47', '#B8860B'),
  },
  {
    id: 90,
    category: 'Natural & Earthy',
    name: 'Leafy Calm',
    description: 'Soft leafy green tones',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#6B8E23', '#8A9B83', '#9DC183', '#7BA56D'),
  },

  // ROMANTIC & FEMININE (91-105)
  {
    id: 91,
    category: 'Romantic & Feminine',
    name: 'Blush Romance',
    description: 'Soft blush pink',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#FFB6C1', '#FFC0CB', '#FFDAB9', '#FFB6D9'),
  },
  {
    id: 92,
    category: 'Romantic & Feminine',
    name: 'Rose Garden',
    description: 'Soft rose tones',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#E13A40', '#FF69B4', '#FFB6D9', '#FFD1DC'),
  },
  {
    id: 93,
    category: 'Romantic & Feminine',
    name: 'Peony Pink',
    description: 'Soft peony pink',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#F1A7C9', '#FFB6D9', '#FFE4E1', '#FFC0CB'),
  },
  {
    id: 94,
    category: 'Romantic & Feminine',
    name: 'Mauve Dreams',
    description: 'Soft mauve tones',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#E0B0FF', '#DDA0DD', '#D8BFD8', '#DA70D6'),
  },
  {
    id: 95,
    category: 'Romantic & Feminine',
    name: 'Dusty Rose',
    description: 'Dusty rose romantic',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#B4767B', '#A0798A', '#C9A8A8', '#E6C7C7'),
  },
  {
    id: 96,
    category: 'Romantic & Feminine',
    name: 'Orchid Silk',
    description: 'Soft orchid tones',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#DA70D6', '#DDA0DD', '#EE82EE', '#FFB6C1'),
  },
  {
    id: 97,
    category: 'Romantic & Feminine',
    name: 'Coral Whisper',
    description: 'Soft coral pink',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#F08080', '#FFB6C1', '#FFDAB9', '#FFA07A'),
  },
  {
    id: 98,
    category: 'Romantic & Feminine',
    name: 'Berry Bliss',
    description: 'Soft berry pink tones',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#E91E63', '#FF1493', '#FFB6D9', '#FF69B4'),
  },
  {
    id: 99,
    category: 'Romantic & Feminine',
    name: 'Lacey Vintage',
    description: 'Vintage lace pink',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#FFE4E1', '#FFF0F5', '#FFB6D9', '#FFDAB9'),
  },
  {
    id: 100,
    category: 'Romantic & Feminine',
    name: 'Lavender Lace',
    description: 'Soft lavender and lace',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#E6E6FA', '#DDA0DD', '#FFB6D9', '#D8BFD8'),
  },
  {
    id: 101,
    category: 'Romantic & Feminine',
    name: 'Baby Pink',
    description: 'Soft baby pink',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#FFC0CB', '#FFB6D9', '#FFDAB9', '#FFE4E1'),
  },
  {
    id: 102,
    category: 'Romantic & Feminine',
    name: 'Cherry Blossom',
    description: 'Soft cherry blossom',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#FFB6C1', '#FFC0CB', '#FFB6D9', '#FFCCCB'),
  },
  {
    id: 103,
    category: 'Romantic & Feminine',
    name: 'Pink Paradise',
    description: 'Soft pink paradise',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#FF69B4', '#FFB6D9', '#FFC0CB', '#FFDAB9'),
  },
  {
    id: 104,
    category: 'Romantic & Feminine',
    name: 'Rose Quartz',
    description: 'Soft rose quartz pink',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#F1A7C9', '#FFB6D9', '#FFDAB9', '#FFE4E1'),
  },
  {
    id: 105,
    category: 'Romantic & Feminine',
    name: 'Blossoming Love',
    description: 'Romantic blossoming tones',
    rooms: ['Bedroom', 'Bathroom'],
    colors: createColorOptions('#FFB6D9', '#FFC0CB', '#FFE4E1', '#FFDAB9'),
  },

  // INDIAN TRADITIONAL (106-120)
  {
    id: 106,
    category: 'Indian Traditional',
    name: 'Indigo Heritage',
    description: 'Deep indigo traditional',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#4B0082', '#240046', '#6A4C93', '#1B1033'),
  },
  {
    id: 107,
    category: 'Indian Traditional',
    name: 'Saffron Spirit',
    description: 'Warm saffron tones',
    rooms: ['Bedroom', 'Dining Room'],
    colors: createColorOptions('#FF9933', '#FF7722', '#DD6611', '#FFAA44'),
  },
  {
    id: 108,
    category: 'Indian Traditional',
    name: 'Temple Gold',
    description: 'Rich temple gold',
    rooms: ['Living Room', 'Dining Room'],
    colors: createColorOptions('#FFD700', '#DAA520', '#B8860B', '#FF9944'),
  },
  {
    id: 109,
    category: 'Indian Traditional',
    name: 'Peacock Blue',
    description: 'Deep peacock blue',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#003366', '#004488', '#0066CC', '#0044AA'),
  },
  {
    id: 110,
    category: 'Indian Traditional',
    name: 'Mehndi Green',
    description: 'Traditional mehndi green',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#228B22', '#1F4D40', '#355E3B', '#2F5233'),
  },
  {
    id: 111,
    category: 'Indian Traditional',
    name: 'Henna Rust',
    description: 'Warm henna rust tones',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#996633', '#8B4513', '#A0522D', '#CD853F'),
  },
  {
    id: 112,
    category: 'Indian Traditional',
    name: 'Maroon Majesty',
    description: 'Deep maroon traditional',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#800000', '#8B0000', '#A71D31', '#660000'),
  },
  {
    id: 113,
    category: 'Indian Traditional',
    name: 'Turmeric Gold',
    description: 'Warm turmeric gold',
    rooms: ['Kitchen', 'Dining Room'],
    colors: createColorOptions('#DAA520', '#FFD700', '#FF9933', '#B8860B'),
  },
  {
    id: 114,
    category: 'Indian Traditional',
    name: 'Lapis Blue',
    description: 'Royal lapis blue',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#0047AB', '#003366', '#004488', '#003D82'),
  },
  {
    id: 115,
    category: 'Indian Traditional',
    name: 'Silk Crimson',
    description: 'Rich silk crimson',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#DC143C', '#8B0000', '#A71D31', '#C41E3A'),
  },
  {
    id: 116,
    category: 'Indian Traditional',
    name: 'Bronze Legacy',
    description: 'Warm bronze tones',
    rooms: ['Living Room', 'Dining Room'],
    colors: createColorOptions('#CD7F32', '#B87333', '#A0522D', '#8B4513'),
  },
  {
    id: 117,
    category: 'Indian Traditional',
    name: 'Royal Purple',
    description: 'Deep royal purple',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#4B0082', '#6A0DAD', '#8B008B', '#663399'),
  },
  {
    id: 118,
    category: 'Indian Traditional',
    name: 'Coral Temple',
    description: 'Warm coral temple tones',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#FF7F50', '#FF6347', '#FF4500', '#FF8C69'),
  },
  {
    id: 119,
    category: 'Indian Traditional',
    name: 'Sapphire Royal',
    description: 'Deep sapphire royal',
    rooms: ['Living Room', 'Bedroom'],
    colors: createColorOptions('#0F3460', '#16213E', '#E94560', '#533483'),
  },
  {
    id: 120,
    category: 'Indian Traditional',
    name: 'Spice Blend',
    description: 'Warm spice blend tones',
    rooms: ['Kitchen', 'Dining Room'],
    colors: createColorOptions('#A0522D', '#8B4513', '#CC5500', '#D2691E'),
  },

  // CONTEMPORARY (121-135)
  {
    id: 121,
    category: 'Contemporary',
    name: 'Graphite Modern',
    description: 'Contemporary graphite',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#2F4F4F', '#36454F', '#404040', '#505050'),
  },
  {
    id: 122,
    category: 'Contemporary',
    name: 'Slate & Steel',
    description: 'Contemporary slate',
    rooms: ['Home Office', 'Modern Home'],
    colors: createColorOptions('#708090', '#778899', '#2F4F4F', '#36454F'),
  },
  {
    id: 123,
    category: 'Contemporary',
    name: 'Urban Gray',
    description: 'Contemporary urban gray',
    rooms: ['Loft', 'Studio'],
    colors: createColorOptions('#A9A9A9', '#808080', '#696969', '#505050'),
  },
  {
    id: 124,
    category: 'Contemporary',
    name: 'Charcoal Modern',
    description: 'Deep charcoal modern',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#36454F', '#2F4F4F', '#1F1F1F', '#404040'),
  },
  {
    id: 125,
    category: 'Contemporary',
    name: 'Silver Lining',
    description: 'Contemporary silver',
    rooms: ['Home Office', 'Modern Home'],
    colors: createColorOptions('#C0C0C0', '#B8B8B8', '#A9A9A9', '#E8E8E8'),
  },
  {
    id: 126,
    category: 'Contemporary',
    name: 'Pewter Tone',
    description: 'Contemporary pewter',
    rooms: ['Kitchen', 'Bathroom'],
    colors: createColorOptions('#C5C5C5', '#B0B0B0', '#808080', '#D3D3D3'),
  },
  {
    id: 127,
    category: 'Contemporary',
    name: 'Titanium',
    description: 'Contemporary titanium',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#A5A5A5', '#969696', '#737373', '#BFBFBF'),
  },
  {
    id: 128,
    category: 'Contemporary',
    name: 'Concrete Chic',
    description: 'Chic concrete tones',
    rooms: ['Loft', 'Modern Home'],
    colors: createColorOptions('#8B8B83', '#A9A9A9', '#696969', '#808080'),
  },
  {
    id: 129,
    category: 'Contemporary',
    name: 'Modern Black',
    description: 'Deep modern black',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#0F0F0F', '#1A1A1A', '#2F2F2F', '#1F1F1F'),
  },
  {
    id: 130,
    category: 'Contemporary',
    name: 'White Space',
    description: 'Contemporary white space',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#FFFFFF', '#FAFAFA', '#F5F5F5', '#F0F0F0'),
  },
  {
    id: 131,
    category: 'Contemporary',
    name: 'Minimalist Dark',
    description: 'Minimalist dark contemporary',
    rooms: ['Home Office', 'Bedroom'],
    colors: createColorOptions('#2F2F2F', '#1F1F1F', '#4F4F4F', '#3F3F3F'),
  },
  {
    id: 132,
    category: 'Contemporary',
    name: 'Sleek Accent',
    description: 'Sleek contemporary accent',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#505050', '#4F4F4F', '#1F1F1F', '#808080'),
  },
  {
    id: 133,
    category: 'Contemporary',
    name: 'Chrome Gray',
    description: 'Contemporary chrome gray',
    rooms: ['Kitchen', 'Bathroom'],
    colors: createColorOptions('#A8A8A8', '#999999', '#7F7F7F', '#C0C0C0'),
  },
  {
    id: 134,
    category: 'Contemporary',
    name: 'Metal Tone',
    description: 'Contemporary metal tone',
    rooms: ['Home Office', 'Modern Home'],
    colors: createColorOptions('#B8B8B8', '#A0A0A0', '#808080', '#696969'),
  },
  {
    id: 135,
    category: 'Contemporary',
    name: 'Futuristic Gray',
    description: 'Futuristic gray tones',
    rooms: ['Modern Home', 'Studio'],
    colors: createColorOptions('#7F7F7F', '#696969', '#5F5F5F', '#8F8F8F'),
  },

  // LUXURY & ACCENT (136-150)
  {
    id: 136,
    category: 'Luxury & Accent',
    name: 'Diamond Bright',
    description: 'Luxury bright diamond',
    rooms: ['Foyer', 'Master Bedroom'],
    colors: createColorOptions('#FFFACD', '#FFFFF0', '#F5F5DC', '#FFFDF7'),
  },
  {
    id: 137,
    category: 'Luxury & Accent',
    name: 'Platinum Luxe',
    description: 'Platinum luxury tones',
    rooms: ['Living Room', 'Dining Room'],
    colors: createColorOptions('#E8E8E8', '#D8D8D8', '#C0C0C0', '#F0F0F0'),
  },
  {
    id: 138,
    category: 'Luxury & Accent',
    name: 'Gold Crown',
    description: 'Royal gold crown',
    rooms: ['Master Bedroom', 'Dining Room'],
    colors: createColorOptions('#FFD700', '#DAA520', '#B8860B', '#FF9944'),
  },
  {
    id: 139,
    category: 'Luxury & Accent',
    name: 'Ruby Royale',
    description: 'Luxury ruby red',
    rooms: ['Dining Room', 'Lounge'],
    colors: createColorOptions('#E0115F', '#C41E3A', '#8B0000', '#DC143C'),
  },
  {
    id: 140,
    category: 'Luxury & Accent',
    name: 'Amethyst Gem',
    description: 'Luxury amethyst gem',
    rooms: ['Master Bedroom', 'Lounge'],
    colors: createColorOptions('#9966CC', '#7744BB', '#6633AA', '#8844DD'),
  },
  {
    id: 141,
    category: 'Luxury & Accent',
    name: 'Onyx Elegance',
    description: 'Black onyx elegance',
    rooms: ['Media Room', 'Master Bedroom'],
    colors: createColorOptions('#0B0C0C', '#1A1A1A', '#2F2F2F', '#000000'),
  },
  {
    id: 142,
    category: 'Luxury & Accent',
    name: 'Ivory Palace',
    description: 'Luxury ivory palace',
    rooms: ['Foyer', 'Bedroom'],
    colors: createColorOptions('#FFFFF0', '#F5F5DC', '#FFFACD', '#F0E68C'),
  },
  {
    id: 143,
    category: 'Luxury & Accent',
    name: 'Jet Black',
    description: 'Luxury jet black',
    rooms: ['Media Room', 'Modern Home'],
    colors: createColorOptions('#000000', '#1A1A1A', '#0F0F0F', '#2F2F2F'),
  },
  {
    id: 144,
    category: 'Luxury & Accent',
    name: 'Silver Stone',
    description: 'Luxury silver stone',
    rooms: ['Living Room', 'Dining Room'],
    colors: createColorOptions('#C0C0C0', '#B8B8B8', '#A9A9A9', '#D3D3D3'),
  },
  {
    id: 145,
    category: 'Luxury & Accent',
    name: 'Copper Luxe',
    description: 'Luxury copper tones',
    rooms: ['Living Room', 'Kitchen'],
    colors: createColorOptions('#B87333', '#CC6600', '#D2691E', '#8B4513'),
  },
  {
    id: 146,
    category: 'Luxury & Accent',
    name: 'Jade Green',
    description: 'Luxury jade green',
    rooms: ['Master Bedroom', 'Lounge'],
    colors: createColorOptions('#00A86B', '#009966', '#007F5C', '#006B54'),
  },
  {
    id: 147,
    category: 'Luxury & Accent',
    name: 'Pearl Lustre',
    description: 'Luxury pearl lustre',
    rooms: ['Bedroom', 'Living Room'],
    colors: createColorOptions('#FDEEF4', '#F0F0F0', '#FAFAFA', '#F5F5F5'),
  },
  {
    id: 148,
    category: 'Luxury & Accent',
    name: 'Bronze Royal',
    description: 'Luxury bronze royal',
    rooms: ['Dining Room', 'Library'],
    colors: createColorOptions('#CD7F32', '#B87333', '#A0522D', '#8B4513'),
  },
  {
    id: 149,
    category: 'Luxury & Accent',
    name: 'Sapphire Gem',
    description: 'Luxury sapphire gem',
    rooms: ['Master Bedroom', 'Library'],
    colors: createColorOptions('#0F3460', '#16213E', '#0047AB', '#003D82'),
  },
  {
    id: 150,
    category: 'Luxury & Accent',
    name: 'Moonlight Glow',
    description: 'Luxury moonlight glow',
    rooms: ['Master Bedroom', 'Spa'],
    colors: createColorOptions('#E8F4F8', '#D0E8F2', '#F0F8FF', '#E0FFFF'),
  },
];

export default homeDesignPacks;
