// UI Packs - Curated color combinations for developers
const generateColorCombinations = (primary, secondary, accent, neutral, success, warning, error, info) => {
  const combinations = [];
  
  // Generate variations of each color
  const generateVariations = (baseColor, count = 10) => {
    const variations = [];
    const normalized = baseColor.replace('#', '');
    const bigint = parseInt(normalized, 16);
    const r = (bigint >> 16) & 255;
    const g = (bigint >> 8) & 255;
    const b = bigint & 255;
    
    for (let i = 0; i < count; i++) {
      const factor = 1 - (i * 0.08);
      const newR = Math.round(r * factor);
      const newG = Math.round(g * factor);
      const newB = Math.round(b * factor);
      const hex = `#${newR.toString(16).padStart(2, '0')}${newG.toString(16).padStart(2, '0')}${newB.toString(16).padStart(2, '0')}`.toUpperCase();
      variations.push(hex);
    }
    return variations;
  };

  // Primary variations
  generateVariations(primary, 10).forEach((color, idx) => {
    combinations.push({
      name: `Primary ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Primary',
    });
  });

  // Secondary variations
  generateVariations(secondary, 10).forEach((color, idx) => {
    combinations.push({
      name: `Secondary ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Secondary',
    });
  });

  // Accent variations
  generateVariations(accent, 10).forEach((color, idx) => {
    combinations.push({
      name: `Accent ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Accent',
    });
  });

  // Neutral variations
  generateVariations(neutral, 10).forEach((color, idx) => {
    combinations.push({
      name: `Neutral ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Neutral',
    });
  });

  // Success variations
  generateVariations(success, 10).forEach((color, idx) => {
    combinations.push({
      name: `Success ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Success',
    });
  });

  // Warning variations
  generateVariations(warning, 10).forEach((color, idx) => {
    combinations.push({
      name: `Warning ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Warning',
    });
  });

  // Error variations
  generateVariations(error, 10).forEach((color, idx) => {
    combinations.push({
      name: `Error ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Error',
    });
  });

  // Info variations
  generateVariations(info, 10).forEach((color, idx) => {
    combinations.push({
      name: `Info ${idx === 0 ? 'Base' : idx}`,
      hex: color,
      category: 'Info',
    });
  });

  return combinations;
};

export const uiPacks = [
  {
    name: 'Royal',
    description: 'Regal and sophisticated color palette for premium designs',
    primary: '#1E3A8A',
    secondary: '#9333EA',
    accent: '#F59E0B',
    neutral: '#64748B',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#3B82F6',
  },
  {
    name: 'Aesthetic',
    description: 'Soft, dreamy colors perfect for modern aesthetic designs',
    primary: '#EC4899',
    secondary: '#F472B6',
    accent: '#FBBF24',
    neutral: '#9CA3AF',
    success: '#34D399',
    warning: '#FBBF24',
    error: '#F87171',
    info: '#60A5FA',
  },
  {
    name: 'Minimalist',
    description: 'Clean, simple palette for minimalist interfaces',
    primary: '#1F2937',
    secondary: '#6B7280',
    accent: '#3B82F6',
    neutral: '#E5E7EB',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#6366F1',
  },
  {
    name: 'NeonGlow',
    description: 'Vibrant neon colors for bold, energetic designs',
    primary: '#00F5FF',
    secondary: '#FF00FF',
    accent: '#FFFF00',
    neutral: '#1A1A1A',
    success: '#00FF00',
    warning: '#FFAA00',
    error: '#FF0066',
    info: '#0066FF',
  },
  {
    name: 'PastelDream',
    description: 'Soft pastel colors for gentle, calming designs',
    primary: '#A8E6CF',
    secondary: '#FFD3B6',
    accent: '#FFAAA5',
    neutral: '#F5F5F5',
    success: '#B8E6B8',
    warning: '#FFE5B4',
    error: '#FFB3BA',
    info: '#B8D4F0',
  },
  {
    name: 'Earthy',
    description: 'Natural earth tones for organic, grounded designs',
    primary: '#8B4513',
    secondary: '#A0522D',
    accent: '#CD853F',
    neutral: '#D2B48C',
    success: '#6B8E23',
    warning: '#DAA520',
    error: '#B22222',
    info: '#4682B4',
  },
  {
    name: 'Sunset',
    description: 'Warm sunset colors for cozy, inviting designs',
    primary: '#FF6B35',
    secondary: '#F7931E',
    accent: '#FFD23F',
    neutral: '#F5E6D3',
    success: '#4ECDC4',
    warning: '#FFE66D',
    error: '#FF6B6B',
    info: '#4A90E2',
  },
  {
    name: 'Oceanic',
    description: 'Cool ocean blues and teals for refreshing designs',
    primary: '#006994',
    secondary: '#00A8CC',
    accent: '#0F4C75',
    neutral: '#E8F4F8',
    success: '#00D9FF',
    warning: '#FFB84D',
    error: '#FF6B6B',
    info: '#4ECDC4',
  },
  {
    name: 'Forest',
    description: 'Deep greens and browns for nature-inspired designs',
    primary: '#2D5016',
    secondary: '#3E7B27',
    accent: '#5A9F3A',
    neutral: '#E8F5E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#D32F2F',
    info: '#2196F3',
  },
  {
    name: 'Monochrome',
    description: 'Elegant grayscale palette for timeless designs',
    primary: '#000000',
    secondary: '#4A4A4A',
    accent: '#808080',
    neutral: '#E0E0E0',
    success: '#4A4A4A',
    warning: '#808080',
    error: '#4A4A4A',
    info: '#808080',
  },
  {
    name: 'RetroPop',
    description: 'Bold retro colors for nostalgic, vibrant designs',
    primary: '#FF1744',
    secondary: '#FF6D00',
    accent: '#FFD600',
    neutral: '#F5F5F5',
    success: '#00E676',
    warning: '#FF9100',
    error: '#D50000',
    info: '#00B0FF',
  },
  {
    name: 'LavenderFields',
    description: 'Soft lavender and purple tones for dreamy designs',
    primary: '#9B59B6',
    secondary: '#E1BEE7',
    accent: '#CE93D8',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'DesertSand',
    description: 'Warm desert tones for arid, sun-kissed designs',
    primary: '#D2691E',
    secondary: '#F4A460',
    accent: '#DEB887',
    neutral: '#FDF5E6',
    success: '#9ACD32',
    warning: '#FFA500',
    error: '#CD5C5C',
    info: '#87CEEB',
  },
  {
    name: 'Frost',
    description: 'Cool icy blues and whites for crisp, clean designs',
    primary: '#B0E0E6',
    secondary: '#E0F7FA',
    accent: '#4DD0E1',
    neutral: '#FFFFFF',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'Ember',
    description: 'Fiery reds and oranges for passionate, energetic designs',
    primary: '#C62828',
    secondary: '#E53935',
    accent: '#FF6F00',
    neutral: '#FFEBEE',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'Glassy',
    description: 'Translucent, glass-like colors for modern UI',
    primary: '#2196F3',
    secondary: '#03A9F4',
    accent: '#00BCD4',
    neutral: '#F5F5F5',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'Cinematic',
    description: 'Deep, dramatic colors for film-inspired designs',
    primary: '#1A1A1A',
    secondary: '#2D2D2D',
    accent: '#FFD700',
    neutral: '#4A4A4A',
    success: '#00FF00',
    warning: '#FFA500',
    error: '#FF0000',
    info: '#00CED1',
  },
  {
    name: 'CandyShop',
    description: 'Sweet, vibrant colors for playful, fun designs',
    primary: '#FF69B4',
    secondary: '#FF1493',
    accent: '#FFD700',
    neutral: '#FFF8DC',
    success: '#98FB98',
    warning: '#FFD700',
    error: '#FF6347',
    info: '#87CEEB',
  },
  {
    name: 'HighContrast',
    description: 'Bold, high-contrast colors for accessibility',
    primary: '#000000',
    secondary: '#FFFFFF',
    accent: '#FFFF00',
    neutral: '#808080',
    success: '#00FF00',
    warning: '#FFA500',
    error: '#FF0000',
    info: '#0000FF',
  },
  {
    name: 'MutedElegance',
    description: 'Sophisticated muted tones for refined designs',
    primary: '#6C757D',
    secondary: '#495057',
    accent: '#ADB5BD',
    neutral: '#F8F9FA',
    success: '#6C757D',
    warning: '#FFC107',
    error: '#DC3545',
    info: '#17A2B8',
  },
  {
    name: 'Cyberpunk',
    description: 'Futuristic neon colors for tech-inspired designs',
    primary: '#00FFFF',
    secondary: '#FF00FF',
    accent: '#FFFF00',
    neutral: '#1A1A2E',
    success: '#00FF00',
    warning: '#FFAA00',
    error: '#FF0066',
    info: '#0066FF',
  },
  {
    name: 'Botanical',
    description: 'Fresh greens and natural tones for organic designs',
    primary: '#2E7D32',
    secondary: '#66BB6A',
    accent: '#81C784',
    neutral: '#F1F8E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#E53935',
    info: '#26A69A',
  },
  {
    name: 'VintagePaper',
    description: 'Warm sepia tones for nostalgic, classic designs',
    primary: '#8B6914',
    secondary: '#D4AF37',
    accent: '#F4E4BC',
    neutral: '#FFF8E7',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#D32F2F',
    info: '#607D8B',
  },
  {
    name: 'Stone',
    description: 'Natural stone grays for solid, grounded designs',
    primary: '#616161',
    secondary: '#9E9E9E',
    accent: '#BDBDBD',
    neutral: '#FAFAFA',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'CoffeeHouse',
    description: 'Rich coffee browns for warm, cozy designs',
    primary: '#3E2723',
    secondary: '#5D4037',
    accent: '#8D6E63',
    neutral: '#EFEBE9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#E57373',
    info: '#90CAF9',
  },
  {
    name: 'ArcticBlue',
    description: 'Cool arctic blues for fresh, crisp designs',
    primary: '#0277BD',
    secondary: '#0288D1',
    accent: '#03A9F4',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'CoralReef',
    description: 'Tropical coral and teal for vibrant designs',
    primary: '#FF6F61',
    secondary: '#FF8A80',
    accent: '#00BCD4',
    neutral: '#FFF3E0',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'VelvetNight',
    description: 'Deep purples and blacks for luxurious designs',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#9C27B0',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#E57373',
    info: '#42A5F5',
  },
  {
    name: 'SunriseGold',
    description: 'Warm golds and oranges for radiant designs',
    primary: '#FF8F00',
    secondary: '#FFA000',
    accent: '#FFC107',
    neutral: '#FFF8E1',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Slate',
    description: 'Cool slate grays for professional designs',
    primary: '#37474F',
    secondary: '#546E7A',
    accent: '#78909C',
    neutral: '#ECEFF1',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'ClayPot',
    description: 'Terracotta and earth tones for rustic designs',
    primary: '#BF360C',
    secondary: '#D84315',
    accent: '#FF6F00',
    neutral: '#FFF3E0',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#D32F2F',
    info: '#0288D1',
  },
  {
    name: 'NeonRetro',
    description: '80s-inspired neon colors for retro designs',
    primary: '#FF00FF',
    secondary: '#00FFFF',
    accent: '#FFFF00',
    neutral: '#1A1A1A',
    success: '#00FF00',
    warning: '#FFAA00',
    error: '#FF0066',
    info: '#0066FF',
  },
  {
    name: 'SugarRush',
    description: 'Sweet pastel colors for delightful designs',
    primary: '#F8BBD0',
    secondary: '#F48FB1',
    accent: '#FFB3BA',
    neutral: '#FFF9F9',
    success: '#C8E6C9',
    warning: '#FFE0B2',
    error: '#FFCDD2',
    info: '#BBDEFB',
  },
  {
    name: 'SoftBlush',
    description: 'Gentle blush pinks for soft, feminine designs',
    primary: '#F8BBD0',
    secondary: '#F48FB1',
    accent: '#E91E63',
    neutral: '#FCE4EC',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'TechBlue',
    description: 'Modern tech blues for digital designs',
    primary: '#1976D2',
    secondary: '#2196F3',
    accent: '#03A9F4',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'IvoryClassic',
    description: 'Elegant ivory and cream for timeless designs',
    primary: '#FFF8E1',
    secondary: '#FFECB3',
    accent: '#FFC107',
    neutral: '#FFFFFF',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'IndigoWave',
    description: 'Deep indigo blues for sophisticated designs',
    primary: '#283593',
    secondary: '#3F51B5',
    accent: '#5C6BC0',
    neutral: '#E8EAF6',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'OliveGrove',
    description: 'Olive greens for natural, earthy designs',
    primary: '#558B2F',
    secondary: '#689F38',
    accent: '#8BC34A',
    neutral: '#F1F8E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#E53935',
    info: '#26A69A',
  },
  {
    name: 'SmokeyMauve',
    description: 'Muted mauve tones for sophisticated designs',
    primary: '#9575CD',
    secondary: '#B39DDB',
    accent: '#CE93D8',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'Twilight',
    description: 'Dusk-inspired purples and blues for evening designs',
    primary: '#311B92',
    secondary: '#512DA8',
    accent: '#7B1FA2',
    neutral: '#EDE7F6',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#E57373',
    info: '#42A5F5',
  },
  {
    name: 'PaperWhite',
    description: 'Clean whites and grays for minimal designs',
    primary: '#FAFAFA',
    secondary: '#F5F5F5',
    accent: '#E0E0E0',
    neutral: '#FFFFFF',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Graphite',
    description: 'Deep graphite grays for industrial designs',
    primary: '#212121',
    secondary: '#424242',
    accent: '#616161',
    neutral: '#F5F5F5',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'TeaLeaf',
    description: 'Warm tea greens for calming designs',
    primary: '#33691E',
    secondary: '#558B2F',
    accent: '#689F38',
    neutral: '#F1F8E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#E53935',
    info: '#26A69A',
  },
  {
    name: 'MintyFresh',
    description: 'Cool mint greens for refreshing designs',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#80DEEA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'Orchid',
    description: 'Elegant orchid purples for refined designs',
    primary: '#BA68C8',
    secondary: '#CE93D8',
    accent: '#E1BEE7',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'AmberTrail',
    description: 'Golden amber tones for warm designs',
    primary: '#FF6F00',
    secondary: '#FF8F00',
    accent: '#FFA000',
    neutral: '#FFF8E1',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'StormySea',
    description: 'Deep storm blues for dramatic designs',
    primary: '#01579B',
    secondary: '#0277BD',
    accent: '#0288D1',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'Lofi',
    description: 'Muted, desaturated colors for chill designs',
    primary: '#8E8E93',
    secondary: '#AEAEB2',
    accent: '#C7C7CC',
    neutral: '#F2F2F7',
    success: '#34C759',
    warning: '#FF9500',
    error: '#FF3B30',
    info: '#007AFF',
  },
  {
    name: 'HazyGrey',
    description: 'Soft hazy grays for dreamy designs',
    primary: '#9E9E9E',
    secondary: '#BDBDBD',
    accent: '#E0E0E0',
    neutral: '#FAFAFA',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'Monarch',
    description: 'Rich monarch oranges for regal designs',
    primary: '#E65100',
    secondary: '#FF6F00',
    accent: '#FF8F00',
    neutral: '#FFF3E0',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'CopperMint',
    description: 'Copper and mint for unique designs',
    primary: '#B87333',
    secondary: '#CD853F',
    accent: '#00BCD4',
    neutral: '#F5F5F5',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'Tangerine',
    description: 'Vibrant tangerine oranges for energetic designs',
    primary: '#FF6F00',
    secondary: '#FF8F00',
    accent: '#FFA000',
    neutral: '#FFF8E1',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Denim',
    description: 'Classic denim blues for casual designs',
    primary: '#1565C0',
    secondary: '#1976D2',
    accent: '#1E88E5',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Hibiscus',
    description: 'Tropical hibiscus pinks for vibrant designs',
    primary: '#E91E63',
    secondary: '#EC407A',
    accent: '#F06292',
    neutral: '#FCE4EC',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'Basil',
    description: 'Fresh basil greens for natural designs',
    primary: '#388E3C',
    secondary: '#43A047',
    accent: '#66BB6A',
    neutral: '#E8F5E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#E53935',
    info: '#26A69A',
  },
  {
    name: 'RoseGold',
    description: 'Luxurious rose gold for elegant designs',
    primary: '#E91E63',
    secondary: '#F06292',
    accent: '#FFB74D',
    neutral: '#FCE4EC',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'PowderRoom',
    description: 'Soft powder blues for delicate designs',
    primary: '#BBDEFB',
    secondary: '#90CAF9',
    accent: '#64B5F6',
    neutral: '#E3F2FD',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#42A5F5',
  },
  {
    name: 'Galaxy',
    description: 'Deep space purples for cosmic designs',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#9C27B0',
    neutral: '#1A1A1A',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#E57373',
    info: '#42A5F5',
  },
  {
    name: 'Charcoal',
    description: 'Rich charcoal grays for bold designs',
    primary: '#212121',
    secondary: '#424242',
    accent: '#616161',
    neutral: '#F5F5F5',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Biscuit',
    description: 'Warm biscuit beiges for cozy designs',
    primary: '#D7CCC8',
    secondary: '#BCAAA4',
    accent: '#A1887F',
    neutral: '#EFEBE9',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'AquaMarine',
    description: 'Fresh aquamarine blues for ocean designs',
    primary: '#00BCD4',
    secondary: '#26C6DA',
    accent: '#4DD0E1',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'SteelBloom',
    description: 'Steel grays with floral accents',
    primary: '#546E7A',
    secondary: '#78909C',
    accent: '#FF6F61',
    neutral: '#ECEFF1',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'Marigold',
    description: 'Bright marigold yellows for cheerful designs',
    primary: '#F57F17',
    secondary: '#FBC02D',
    accent: '#FDD835',
    neutral: '#FFFDE7',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Pebble',
    description: 'Smooth pebble grays for natural designs',
    primary: '#757575',
    secondary: '#9E9E9E',
    accent: '#BDBDBD',
    neutral: '#FAFAFA',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'SunlitMeadow',
    description: 'Bright meadow greens for fresh designs',
    primary: '#689F38',
    secondary: '#7CB342',
    accent: '#8BC34A',
    neutral: '#F1F8E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#E53935',
    info: '#26A69A',
  },
  {
    name: 'Barista',
    description: 'Rich coffee tones for warm designs',
    primary: '#5D4037',
    secondary: '#6D4C41',
    accent: '#8D6E63',
    neutral: '#EFEBE9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#E57373',
    info: '#90CAF9',
  },
  {
    name: 'Porcelain',
    description: 'Delicate porcelain whites for elegant designs',
    primary: '#FAFAFA',
    secondary: '#F5F5F5',
    accent: '#E0E0E0',
    neutral: '#FFFFFF',
    success: '#C8E6C9',
    warning: '#FFE0B2',
    error: '#FFCDD2',
    info: '#BBDEFB',
  },
  {
    name: 'NeonPastel',
    description: 'Soft neon pastels for modern designs',
    primary: '#FFB3BA',
    secondary: '#BAFFC9',
    accent: '#BAE1FF',
    neutral: '#FFFFBA',
    success: '#BAFFC9',
    warning: '#FFDFBA',
    error: '#FFB3BA',
    info: '#BAE1FF',
  },
  {
    name: 'Glacier',
    description: 'Cool glacier blues for icy designs',
    primary: '#B3E5FC',
    secondary: '#81D4FA',
    accent: '#4FC3F7',
    neutral: '#E1F5FE',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#29B6F6',
  },
  {
    name: 'EmberGlow',
    description: 'Glowing ember oranges for warm designs',
    primary: '#FF6F00',
    secondary: '#FF8F00',
    accent: '#FFA000',
    neutral: '#FFF3E0',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Dune',
    description: 'Sandy dune beiges for desert designs',
    primary: '#D7CCC8',
    secondary: '#EFEBE9',
    accent: '#BCAAA4',
    neutral: '#FAFAFA',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'OrchidMist',
    description: 'Misty orchid purples for ethereal designs',
    primary: '#BA68C8',
    secondary: '#CE93D8',
    accent: '#E1BEE7',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'Harbor',
    description: 'Nautical harbor blues for maritime designs',
    primary: '#1565C0',
    secondary: '#1976D2',
    accent: '#1E88E5',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Cocoa',
    description: 'Rich cocoa browns for chocolate designs',
    primary: '#5D4037',
    secondary: '#6D4C41',
    accent: '#8D6E63',
    neutral: '#EFEBE9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#E57373',
    info: '#90CAF9',
  },
  {
    name: 'ElectricLime',
    description: 'Electric lime greens for vibrant designs',
    primary: '#CDDC39',
    secondary: '#D4E157',
    accent: '#DCE775',
    neutral: '#F9FBE7',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Moss',
    description: 'Deep moss greens for natural designs',
    primary: '#33691E',
    secondary: '#558B2F',
    accent: '#689F38',
    neutral: '#F1F8E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#E53935',
    info: '#26A69A',
  },
  {
    name: 'BlushStone',
    description: 'Blush pinks with stone grays',
    primary: '#F8BBD0',
    secondary: '#F48FB1',
    accent: '#9E9E9E',
    neutral: '#FAFAFA',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'RoyalVelvet',
    description: 'Luxurious royal velvet purples',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#9C27B0',
    neutral: '#EDE7F6',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#E57373',
    info: '#42A5F5',
  },
  {
    name: 'Aurora',
    description: 'Northern lights inspired colors',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#80DEEA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'Parchment',
    description: 'Ancient parchment beiges',
    primary: '#EFEBE9',
    secondary: '#D7CCC8',
    accent: '#BCAAA4',
    neutral: '#FAFAFA',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'NightSky',
    description: 'Deep night sky blues',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'LavenderSmoke',
    description: 'Smoky lavender purples',
    primary: '#9575CD',
    secondary: '#B39DDB',
    accent: '#CE93D8',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'Poppy',
    description: 'Bright poppy reds',
    primary: '#D32F2F',
    secondary: '#E53935',
    accent: '#EF5350',
    neutral: '#FFEBEE',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'Rainforest',
    description: 'Deep rainforest greens',
    primary: '#1B5E20',
    secondary: '#2E7D32',
    accent: '#388E3C',
    neutral: '#E8F5E9',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#E53935',
    info: '#26A69A',
  },
  {
    name: 'Sepia',
    description: 'Vintage sepia tones',
    primary: '#8B6914',
    secondary: '#A1887F',
    accent: '#BCAAA4',
    neutral: '#FFF8E7',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#D32F2F',
    info: '#607D8B',
  },
  {
    name: 'VelvetRose',
    description: 'Luxurious velvet rose pinks',
    primary: '#C2185B',
    secondary: '#E91E63',
    accent: '#F06292',
    neutral: '#FCE4EC',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'SlateMint',
    description: 'Slate grays with mint accents',
    primary: '#546E7A',
    secondary: '#78909C',
    accent: '#4DD0E1',
    neutral: '#ECEFF1',
    success: '#4CAF50',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#00BCD4',
  },
  {
    name: 'Brass',
    description: 'Warm brass metallics',
    primary: '#B8860B',
    secondary: '#DAA520',
    accent: '#FFD700',
    neutral: '#FFF8DC',
    success: '#66BB6A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Lagoon',
    description: 'Tropical lagoon blues',
    primary: '#00838F',
    secondary: '#00ACC1',
    accent: '#26C6DA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'Honeycomb',
    description: 'Golden honeycomb yellows',
    primary: '#F57F17',
    secondary: '#FBC02D',
    accent: '#FDD835',
    neutral: '#FFFDE7',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'MidnightBlue',
    description: 'Deep midnight blues',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'Cerulean',
    description: 'Bright cerulean blues',
    primary: '#0277BD',
    secondary: '#0288D1',
    accent: '#03A9F4',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'Driftwood',
    description: 'Weathered driftwood browns',
    primary: '#8D6E63',
    secondary: '#A1887F',
    accent: '#BCAAA4',
    neutral: '#EFEBE9',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'OrchidTea',
    description: 'Orchid purples with tea greens',
    primary: '#BA68C8',
    secondary: '#CE93D8',
    accent: '#8BC34A',
    neutral: '#F3E5F5',
    success: '#4CAF50',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'NeonFrost',
    description: 'Cool neon frost blues',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#80DEEA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'Wheatfield',
    description: 'Golden wheat field yellows',
    primary: '#FBC02D',
    secondary: '#FDD835',
    accent: '#FFEB3B',
    neutral: '#FFFDE7',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'CopperSun',
    description: 'Copper and sun oranges',
    primary: '#B87333',
    secondary: '#CD853F',
    accent: '#FF6F00',
    neutral: '#FFF3E0',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'MistyLilac',
    description: 'Misty lilac purples',
    primary: '#BA68C8',
    secondary: '#CE93D8',
    accent: '#E1BEE7',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'RegalSlate',
    description: 'Regal slate grays',
    primary: '#37474F',
    secondary: '#546E7A',
    accent: '#78909C',
    neutral: '#ECEFF1',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'MidnightBloom',
    description: 'Deep midnight blues with floral accents',
    primary: '#1A237E',
    secondary: '#283593',
    accent: '#5C6BC0',
    neutral: '#E8EAF6',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'SageGarden',
    description: 'Calming sage greens for peaceful designs',
    primary: '#87AE73',
    secondary: '#A8C090',
    accent: '#C4D4B0',
    neutral: '#F5F5F0',
    success: '#9BC88B',
    warning: '#D4A574',
    error: '#C88B7A',
    info: '#90B8C8',
  },
  {
    name: 'MintFresh',
    description: 'Fresh mint greens for clean designs',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#80DEEA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'AutumnLeaves',
    description: 'Warm autumn leaf colors',
    primary: '#D84315',
    secondary: '#FF5722',
    accent: '#FF7043',
    neutral: '#FBE9E7',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'LavenderMist',
    description: 'Soft lavender mist purples',
    primary: '#9575CD',
    secondary: '#B39DDB',
    accent: '#CE93D8',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'EmeraldForest',
    description: 'Rich emerald forest greens',
    primary: '#1B5E20',
    secondary: '#2E7D32',
    accent: '#4CAF50',
    neutral: '#E8F5E9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'DeepOcean',
    description: 'Deep ocean navy blues',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'PeachBlush',
    description: 'Soft peach blush tones',
    primary: '#FF8A65',
    secondary: '#FFAB91',
    accent: '#FFCCBC',
    neutral: '#FFF3E0',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'MysticPurple',
    description: 'Mystic purple and violet',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#9C27B0',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'TropicalParadise',
    description: 'Vibrant tropical paradise colors',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#FF6F00',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'CharcoalSmoke',
    description: 'Deep charcoal and smoke grays',
    primary: '#212121',
    secondary: '#424242',
    accent: '#616161',
    neutral: '#F5F5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'LimeZest',
    description: 'Fresh lime zest greens',
    primary: '#827717',
    secondary: '#9E9D24',
    accent: '#CDDC39',
    neutral: '#F9FBE7',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'MeadowGreen',
    description: 'Fresh meadow greens',
    primary: '#33691E',
    secondary: '#558B2F',
    accent: '#689F38',
    neutral: '#F1F8E9',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'CobaltSky',
    description: 'Deep cobalt sky blues',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'SunsetOrange',
    description: 'Vibrant sunset orange tones',
    primary: '#FF6B35',
    secondary: '#F7931E',
    accent: '#FFB347',
    neutral: '#FFF3E0',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'ForestMist',
    description: 'Mystical forest mist greens',
    primary: '#2D5016',
    secondary: '#3E7B27',
    accent: '#5A9F3A',
    neutral: '#E8F5E9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'BerryBurst',
    description: 'Fresh berry burst colors',
    primary: '#8B1538',
    secondary: '#C2185B',
    accent: '#E91E63',
    neutral: '#FCE4EC',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'DesertSun',
    description: 'Warm desert sun tones',
    primary: '#D2691E',
    secondary: '#CD853F',
    accent: '#DEB887',
    neutral: '#FFF8DC',
    success: '#9CCC65',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#81D4FA',
  },
  {
    name: 'TwilightPurple',
    description: 'Elegant twilight purple',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#9C27B0',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'MintJulep',
    description: 'Fresh mint julep greens',
    primary: '#00C896',
    secondary: '#4ECDC4',
    accent: '#95E1D3',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'CrimsonVelvet',
    description: 'Luxurious crimson velvet',
    primary: '#8B0000',
    secondary: '#B71C1C',
    accent: '#D32F2F',
    neutral: '#FFEBEE',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'SkylineBlue',
    description: 'Urban skyline blue',
    primary: '#1565C0',
    secondary: '#1976D2',
    accent: '#1E88E5',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'LemonZest',
    description: 'Bright lemon zest yellow',
    primary: '#FDD835',
    secondary: '#FFEB3B',
    accent: '#FFF176',
    neutral: '#FFFDE7',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'DeepForest',
    description: 'Rich deep forest greens',
    primary: '#1B5E20',
    secondary: '#2E7D32',
    accent: '#388E3C',
    neutral: '#E8F5E9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'RoyalPurple',
    description: 'Regal royal purple',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#8E24AA',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'MidnightNavy',
    description: 'Deep midnight navy',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'SpringBloom',
    description: 'Fresh spring bloom colors',
    primary: '#E91E63',
    secondary: '#F06292',
    accent: '#F8BBD0',
    neutral: '#FCE4EC',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'ElectricBlue',
    description: 'Vibrant electric blue',
    primary: '#2196F3',
    secondary: '#42A5F5',
    accent: '#64B5F6',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'GoldenSunset',
    description: 'Warm golden sunset',
    primary: '#FF6F00',
    secondary: '#FF8F00',
    accent: '#FFA000',
    neutral: '#FFF8E1',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'EmeraldJade',
    description: 'Precious emerald jade',
    primary: '#00695C',
    secondary: '#00897B',
    accent: '#26A69A',
    neutral: '#E0F2F1',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'RoseQuartz',
    description: 'Delicate rose quartz',
    primary: '#E91E63',
    secondary: '#EC407A',
    accent: '#F48FB1',
    neutral: '#FCE4EC',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'OceanBreeze',
    description: 'Fresh ocean breeze',
    primary: '#0277BD',
    secondary: '#0288D1',
    accent: '#03A9F4',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'AmberFire',
    description: 'Glowing amber fire',
    primary: '#FF6F00',
    secondary: '#FF8F00',
    accent: '#FFA000',
    neutral: '#FFF8E1',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'LavenderDream',
    description: 'Soft lavender dream',
    primary: '#9575CD',
    secondary: '#B39DDB',
    accent: '#CE93D8',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'TealWaters',
    description: 'Calm teal waters',
    primary: '#00695C',
    secondary: '#00897B',
    accent: '#26A69A',
    neutral: '#E0F2F1',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'CherryBlossom',
    description: 'Pink cherry blossom',
    primary: '#E91E63',
    secondary: '#EC407A',
    accent: '#F48FB1',
    neutral: '#FCE4EC',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'SapphireBlue',
    description: 'Precious sapphire blue',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'PeachCream',
    description: 'Soft peach cream',
    primary: '#FF8A65',
    secondary: '#FFAB91',
    accent: '#FFCCBC',
    neutral: '#FFF3E0',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'IndigoNight',
    description: 'Deep indigo night',
    primary: '#1A237E',
    secondary: '#283593',
    accent: '#3949AB',
    neutral: '#E8EAF6',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'MintCream',
    description: 'Fresh mint cream',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#80DEEA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'RubyRed',
    description: 'Bold ruby red',
    primary: '#B71C1C',
    secondary: '#C62828',
    accent: '#D32F2F',
    neutral: '#FFEBEE',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'AzureSky',
    description: 'Bright azure sky',
    primary: '#0288D1',
    secondary: '#03A9F4',
    accent: '#29B6F6',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'TurquoiseSea',
    description: 'Vibrant turquoise sea',
    primary: '#00897B',
    secondary: '#00ACC1',
    accent: '#26C6DA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'LimeFresh',
    description: 'Fresh lime green',
    primary: '#827717',
    secondary: '#9E9D24',
    accent: '#CDDC39',
    neutral: '#F9FBE7',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'VioletMist',
    description: 'Soft violet mist',
    primary: '#6A1B9A',
    secondary: '#8E24AA',
    accent: '#AB47BC',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'OceanWave',
    description: 'Calm ocean wave',
    primary: '#0277BD',
    secondary: '#0288D1',
    accent: '#03A9F4',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'ForestPath',
    description: 'Mystical forest path',
    primary: '#1B5E20',
    secondary: '#2E7D32',
    accent: '#4CAF50',
    neutral: '#E8F5E9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'MintLeaf',
    description: 'Fresh mint leaf',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#80DEEA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'CoralPink',
    description: 'Soft coral pink',
    primary: '#FF6B6B',
    secondary: '#FF8E8E',
    accent: '#FFB3B3',
    neutral: '#FFEBEE',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'LavenderField',
    description: 'Peaceful lavender field',
    primary: '#9575CD',
    secondary: '#B39DDB',
    accent: '#CE93D8',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'TealHorizon',
    description: 'Calm teal horizon',
    primary: '#00695C',
    secondary: '#00897B',
    accent: '#26A69A',
    neutral: '#E0F2F1',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'CherryRed',
    description: 'Bold cherry red',
    primary: '#B71C1C',
    secondary: '#C62828',
    accent: '#D32F2F',
    neutral: '#FFEBEE',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'GoldenSun',
    description: 'Radiant golden sun',
    primary: '#F57F17',
    secondary: '#FBC02D',
    accent: '#FDD835',
    neutral: '#FFFDE7',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'PlumVelvet',
    description: 'Luxurious plum velvet',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#8E24AA',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'TurquoiseDream',
    description: 'Dreamy turquoise',
    primary: '#00897B',
    secondary: '#00ACC1',
    accent: '#26C6DA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'LimeZing',
    description: 'Zesty lime green',
    primary: '#827717',
    secondary: '#9E9D24',
    accent: '#CDDC39',
    neutral: '#F9FBE7',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'VioletStorm',
    description: 'Bold violet storm',
    primary: '#6A1B9A',
    secondary: '#8E24AA',
    accent: '#AB47BC',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'SunsetVibes',
    description: 'Energetic sunset vibes',
    primary: '#FF6B35',
    secondary: '#F7931E',
    accent: '#FFB347',
    neutral: '#FFF3E0',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'MysticForest',
    description: 'Enchanting mystic forest',
    primary: '#1B5E20',
    secondary: '#2E7D32',
    accent: '#4CAF50',
    neutral: '#E8F5E9',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'RoyalCrown',
    description: 'Majestic royal crown',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#9C27B0',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'TropicalBreeze',
    description: 'Fresh tropical breeze',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#FF6F00',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'VelvetRose',
    description: 'Luxurious velvet rose',
    primary: '#E91E63',
    secondary: '#EC407A',
    accent: '#F48FB1',
    neutral: '#FCE4EC',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'NavyStorm',
    description: 'Powerful navy storm',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'EmeraldGarden',
    description: 'Lush emerald garden',
    primary: '#00695C',
    secondary: '#00897B',
    accent: '#26A69A',
    neutral: '#E0F2F1',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'AmberSun',
    description: 'Radiant amber sun',
    primary: '#FF6F00',
    secondary: '#FF8F00',
    accent: '#FFA000',
    neutral: '#FFF8E1',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'LavenderTwilight',
    description: 'Soft lavender twilight',
    primary: '#9575CD',
    secondary: '#B39DDB',
    accent: '#CE93D8',
    neutral: '#F3E5F5',
    success: '#A5D6A7',
    warning: '#FFE082',
    error: '#EF9A9A',
    info: '#90CAF9',
  },
  {
    name: 'GoldenDawn',
    description: 'Bright golden dawn',
    primary: '#F57F17',
    secondary: '#FBC02D',
    accent: '#FDD835',
    neutral: '#FFFDE7',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'PlumElegance',
    description: 'Sophisticated plum elegance',
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#8E24AA',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'OceanMist',
    description: 'Gentle ocean mist',
    primary: '#0277BD',
    secondary: '#0288D1',
    accent: '#03A9F4',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'RosePetals',
    description: 'Delicate rose petals',
    primary: '#E91E63',
    secondary: '#F06292',
    accent: '#F8BBD0',
    neutral: '#FCE4EC',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'MidnightStar',
    description: 'Shimmering midnight star',
    primary: '#1A237E',
    secondary: '#283593',
    accent: '#3949AB',
    neutral: '#E8EAF6',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'MintFrost',
    description: 'Cool mint frost',
    primary: '#00BCD4',
    secondary: '#4DD0E1',
    accent: '#80DEEA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FFC107',
    error: '#F44336',
    info: '#00ACC1',
  },
  {
    name: 'CoralSunset',
    description: 'Warm coral sunset',
    primary: '#FF6B6B',
    secondary: '#FF8E8E',
    accent: '#FFB3B3',
    neutral: '#FFEBEE',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
    info: '#64B5F6',
  },
  {
    name: 'SapphireDream',
    description: 'Precious sapphire dream',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#1976D2',
    neutral: '#E3F2FD',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'LimeSpark',
    description: 'Energetic lime spark',
    primary: '#827717',
    secondary: '#9E9D24',
    accent: '#CDDC39',
    neutral: '#F9FBE7',
    success: '#8BC34A',
    warning: '#FFC107',
    error: '#F44336',
    info: '#2196F3',
  },
  {
    name: 'VioletBloom',
    description: 'Beautiful violet bloom',
    primary: '#6A1B9A',
    secondary: '#8E24AA',
    accent: '#AB47BC',
    neutral: '#F3E5F5',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    info: '#42A5F5',
  },
  {
    name: 'AzureWave',
    description: 'Smooth azure wave',
    primary: '#0288D1',
    secondary: '#03A9F4',
    accent: '#29B6F6',
    neutral: '#E1F5FE',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
  {
    name: 'TurquoiseFlow',
    description: 'Flowing turquoise',
    primary: '#00897B',
    secondary: '#00ACC1',
    accent: '#26C6DA',
    neutral: '#E0F7FA',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#00BCD4',
  },
].map((pack) => ({
  ...pack,
  combinations: generateColorCombinations(
    pack.primary,
    pack.secondary,
    pack.accent,
    pack.neutral,
    pack.success,
    pack.warning,
    pack.error,
    pack.info,
  ),
}));

export default uiPacks;
